### PR TITLE
Updates to command descriptions

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
I know just typing !invite makes it join #toxirc but #toxirc seems more utilitarian (bot owners might join it) but I'm not sure users would join it so I would personally just stick to specified channel for the description instead.

The rest are just suggestions for clarify (in my mind).

**Comment by ghost** [comment]
I would also switch to using ! instead of plain text now that the bot filters these out to prevent someone joining tox saying "help" because they need help and the bot says yes sir, what did you want.. :)

**Review by e0ff — CHANGES_REQUESTED** [review]
Please remove the exclamation marks from the command names. All of these commands are sent directly to the bot so they don't need to be distinguished from regular conversation. Also can you please align everything.

**Comment by ghost** [comment]
Updated with requested change.

**Review by e0ff — APPROVED** [review]

**Pull request merged**
